#!/usr/bin/env bash
# Generated by OpenCode - Pyramid OS archiso profile
# Pyramid OS 1.0.0-alpha "Great Sphinx" | Arch Linux + Hyprland + QML
# Constitution Law 4: Build Reproducibility

iso_name="pyramid-os"
iso_label="PYRAMID_OS_100"
iso_publisher="Pyramid OS <https://github.com/SulphArk/Pyramid-OS->"
iso_application="Pyramid OS 1.0.0-alpha (Great Sphinx)"
iso_version="1.0.0"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito'
           'uefi-ia32.grub.esp' 'uefi-x64.systemd-boot.esp'
           'uefi-ia32.grub.eltorito' 'uefi-x64.systemd-boot.eltorito')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/Installation_guide"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/bar-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/close-all.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/idle-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/monitor-scaling.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/open-cwd.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/screenshot.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/system-lock.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/tiled-fullscreen.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/webapp.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/window-gaps.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/window-pop.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/window-transparency.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/window-width.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/workspace-layout.sh"]="0:0:755"
)
