// Generated by OpenCode - Pyramid OS Calamares slideshow
import QtQuick 2.15
import QtQuick.Layouts 1.3

Rectangle {
    color: "#1A1A1A"
    ColumnLayout {
        anchors.centerIn: parent
        spacing: 20
        Text {
            text: "▲ Pyramid OS"
            color: "#C9A84C"
            font.pixelSize: 42
            font.family: "Inter"
            Layout.alignment: Qt.AlignHCenter
        }
        Text {
            text: "Great Sphinx — 1.0.0-alpha\nArch. Hyprland. QML. Yours."
            color: "#E8E2C8"
            font.pixelSize: 18
            horizontalAlignment: Text.AlignHCenter
            Layout.alignment: Qt.AlignHCenter
        }
        Text {
            text: "Minimal base • Beautiful core • Extensible apex"
            color: "#7A7A7A"
            font.pixelSize: 14
            Layout.alignment: Qt.AlignHCenter
        }
    }
}
