# Generated by OpenCode - Pyramid OS zshrc (skel)
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
setopt appendhistory sharehistory hist_ignore_dups
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
[[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
alias ls='ls --color=auto'
alias ll='ls -lah'
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias vim='nvim'
alias cat='bat --style=plain 2>/dev/null || cat'
PROMPT='%F{#C9A84C}▲ %F{#E8E2C8}%~ %F{#D4AF37}›%f '
if [[ -z $DISPLAY && $(tty) == /dev/tty1 && -z $WAYLAND_DISPLAY ]]; then
  exec Hyprland
fi
