#!/usr/bin/env bash
# Generated by OpenCode - Pyramid OS Emergency CLI Installer
# Fallback when Calamares fails. Wipes target disk. Law 5: Base is boring, just works.
# Usage: sudo ./install.sh (run inside live ISO)

set -euo pipefail
IFS=$'\n\t'

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}🔺 Pyramid OS - CLI Installer (Emergency)${NC}"
echo -e "${RED}WARNING: This will WIPE the selected disk!${NC}"
read -rp "Type 'yes' to continue: " confirm
[[ "$confirm" != "yes" ]] && { echo "Aborted."; exit 1; }

echo "Available disks:"
lsblk -d -o NAME,SIZE,MODEL,TYPE | grep -E "disk|NAME"
read -rp "Enter disk to install (e.g., /dev/sda or /dev/nvme0n1): " DISK
[[ -b "$DISK" ]] || { echo "Not a block device: $DISK"; exit 1; }

read -rp "Enter hostname [pyramid]: " HOSTNAME
HOSTNAME=${HOSTNAME:-pyramid}
read -rp "Enter username [pyramid]: " USERNAME
USERNAME=${USERNAME:-pyramid}
read -rsp "Enter password: " PASSWORD
echo ""
[[ -z "$PASSWORD" ]] && { echo "Password cannot be empty"; exit 1; }

# ── partition (GPT, ESP + root) ────────────────────────────
echo -e "${GREEN}▶ Partitioning $DISK...${NC}"
parted -s "$DISK" mklabel gpt
parted -s "$DISK" mkpart primary fat32 1MiB 512MiB
parted -s "$DISK" set 1 esp on
parted -s "$DISK" mkpart primary ext4 512MiB 100%

# Handle nvme p1 vs sda1 naming
if [[ "$DISK" == *"nvme"* ]]; then P1="${DISK}p1"; P2="${DISK}p2"; else P1="${DISK}1"; P2="${DISK}2"; fi

# ── format ─────────────────────────────────────────────────
echo "▶ Formatting..."
mkfs.fat -F32 "$P1"
mkfs.ext4 -L pyramid-root "$P2"

# ── mount ──────────────────────────────────────────────────
mount "$P2" /mnt
mkdir -p /mnt/boot
mount "$P1" /mnt/boot

# ── pacstrap base ──────────────────────────────────────────
echo -e "${GREEN}▶ Installing base system (pacstrap)...${NC}"
# Use packages.x86_64 from repo if available, else minimal
if [[ -f "$(dirname "$0")/../packages.x86_64" ]]; then
  mapfile -t PKGS < <(grep -v '^#' "$(dirname "$0")/../packages.x86_64" | grep -v '^$' | grep -v '^###')
  pacstrap /mnt "${PKGS[@]}"
else
  pacstrap /mnt base base-devel linux-lts linux-firmware hyprland pipewire pipewire-pulse wireplumber networkmanager sddm git
fi
genfstab -U /mnt >> /mnt/etc/fstab

# ── chroot setup ───────────────────────────────────────────
echo "▶ Configuring system..."
arch-chroot /mnt /bin/bash <<EOF
set -euo pipefail
ln -sf /usr/share/zoneinfo/UTC /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "$HOSTNAME" > /etc/hostname
cat > /etc/hosts <<HOSTS
127.0.0.1 localhost
::1       localhost
127.0.1.1 $HOSTNAME.localdomain $HOSTNAME
HOSTS

# GRUB
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=Pyramid --recheck 2>/dev/null || grub-install --target=i386-pc "$DISK" 2>/dev/null || true
grub-mkconfig -o /boot/grub/grub.cfg

# User
useradd -m -G wheel,audio,video,network,storage,optical,power -s /bin/zsh "$USERNAME"
echo "$USERNAME:$PASSWORD" | chpasswd
echo "root:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/10-wheel
chmod 440 /etc/sudoers.d/10-wheel

# Enable services (Law 2)
systemctl enable NetworkManager
systemctl enable sddm
# Bluetooth/CUPS stay disabled

# Copy Pyramid configs if present in live ISO
if [[ -d /root/pyramid-configs ]]; then
  cp -r /root/pyramid-configs/* /home/$USERNAME/.config/ 2>/dev/null || true
  chown -R $USERNAME:$USERNAME /home/$USERNAME/.config/
fi
# Fallback: copy skel
cp -a /etc/skel/. /home/$USERNAME/ 2>/dev/null || true
chown -R $USERNAME:$USERNAME /home/$USERNAME/
EOF

umount -R /mnt
echo -e "${GREEN}✓ Pyramid OS installed to $DISK! Remove USB and reboot.${NC}"
