#!/usr/bin/env bash
# Generated by OpenCode - Pyramid OS First Boot Welcome
# Runs once per user via autostart or systemd user service

set -euo pipefail
MARKER="$HOME/.local/share/pyramid/welcome-done"
if [[ -f "$MARKER" ]]; then exit 0; fi

# Use notify-send if available, else echo
if command -v notify-send &>/dev/null; then
  notify-send -a "Pyramid OS" -i pyramid "▲ Welcome to Pyramid OS" "Great Sphinx 1.0.0 — press SUPER+SPACE for launcher, SUPER+RETURN for terminal"
else
  echo "▲ Welcome to Pyramid OS — Great Sphinx 1.0.0"
  echo "  SUPER+SPACE = launcher | SUPER+RETURN = terminal | SUPER+Q = close"
fi

mkdir -p "$(dirname "$MARKER")"
touch "$MARKER"
